### PR TITLE
Feature/cake upgrade

### PR DESCRIPTION
**Pull request by dweggemans**
Upgraded netstandards target version to 2.0 to match Cake build target. 

Upgraded Cake packages to latest stable 0.26.1

### CODE REVIEW

**Comment by dweggemans** [comment]
The build runs fine locally, so I can't tell exactly why it does not work. Might be related to https://github.com/cake-contrib/Cake.Codecov/issues/17

**Comment by gep13** [comment]
@dweggemans is there a reason that you closed this Pull Request?

**Comment by gep13** [comment]
@dweggemans oh, I see, looks like this has already been taken care of.  Apologies that this PR was missed.

**Comment by dweggemans** [comment]
Exactly. This PR is obsolete with release 2.1.0

**Pull request closed without merging**
